# Generated by Django 3.2.16 on 2023-02-07 09:39

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareProvider',
            fields=[
                ('careprovider_username', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('business_name', models.CharField(default='add_business_name', max_length=100)),
                ('type_of_care', models.CharField(choices=[('ELDERLYCARE', 'Elderly Care'), ('GP', 'General Practioner'), ('CAREWORKER', 'Care Worker'), ('HOMECARER', 'Home Carer'), ('ORTHOPEDICS', 'Orthopedics'), ('OCCUPATIONAL', 'Occupational Therapist'), ('CHIROPODISTS', 'Chiropodists'), ('PHYSIOTHERAPY', 'Physiotherapy'), ('SWIFTCARE', 'Swift Medical Care'), ('DEMENTIA', 'Dementia Support')], default='ELDERLY CARE', max_length=25)),
                ('main_contact_name', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=250)),
                ('county', models.CharField(choices=[('CARLOW', 'Carlow'), ('CAVAN', 'Cavan'), ('CLARE', 'Clare'), ('CORK', 'Cork'), ('DONEGAL', 'Donegal'), ('DUBLIN', 'Dublin'), ('GALWAY', 'Galway'), ('KERRY', 'Kerry'), ('KILDARE', 'Kildare'), ('KILKENNY', 'Kilkenny'), ('LAOISE', 'Laois'), ('LEITRIM', 'Leitrim'), ('LIMERICK', 'Limerick'), ('LONGFORD', 'Longford'), ('LOUTH', 'Louth'), ('MAYO', 'Mayo'), ('MEATH', 'Meath'), ('MONAGHAN', 'Monaghan'), ('OFFALY', 'Offaly'), ('ROSCOMMON', 'Roscommon'), ('SLIGO', 'Sligo'), ('TIPPERARY', 'Tipperary'), ('WATERFORD', 'Waterford'), ('WESTMEATH', 'Westmeath'), ('WEXFORD', 'Wexford'), ('WICKLOW', 'Wicklow')], default='DUBLIN', max_length=9)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('disabled_parking', models.BooleanField()),
                ('provider_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('description', models.TextField(blank=True, null=True)),
                ('provider_approved_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved_careprovider')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='provider_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareProviderComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('careprovider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careprovider_comments', to='caresearch.careprovider')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
