# Generated by Django 3.2.16 on 2023-01-19 15:56

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareProvider',
            fields=[
                ('careprovider_username', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=200, unique=True)),
                ('main_contact_name', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=250)),
                ('address_line_2', models.CharField(blank=True, max_length=250)),
                ('address_line_3', models.CharField(blank=True, max_length=250)),
                ('county', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=8)),
                ('phone_number', models.IntegerField()),
                ('outofhours_phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('disabled_parking', models.BooleanField()),
                ('provider_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('provider_approved_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved_careprovider')], default=0)),
                ('likes', models.ManyToManyField(blank=True, related_name='provider_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareSeeker',
            fields=[
                ('careseeker_username', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=250)),
                ('address_line_2', models.CharField(blank=True, max_length=250)),
                ('address_line_3', models.CharField(blank=True, max_length=250)),
                ('county', models.CharField(max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=8)),
                ('landline_phone_number', models.IntegerField()),
                ('mobile_phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('needs_assistance', models.BooleanField()),
                ('disabled_parking', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CareProviderComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('careprovider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careprovider_comments', to='caresearch.careprovider')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
