# Generated by Django 3.2.16 on 2023-01-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caresearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careprovider',
            name='type_of_care',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
