# Generated by Django 3.2.16 on 2023-01-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caresearch', '0002_careprovider_type_of_care'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careprovider',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='careprovider',
            name='address_line_3',
        ),
        migrations.RemoveField(
            model_name='careprovider',
            name='outofhours_phone',
        ),
        migrations.RemoveField(
            model_name='careprovider',
            name='postcode',
        ),
    ]
