# Generated by Django 3.2.16 on 2023-02-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caresearch', '0004_auto_20230130_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careprovider',
            name='password',
        ),
    ]
