# Generated by Django 3.2.16 on 2023-02-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caresearch', '0005_remove_careprovider_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careprovider',
            name='business_name',
        ),
    ]
