# Generated by Django 3.2.16 on 2023-02-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caresearch', '0006_remove_careprovider_business_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareSeeker',
        ),
        migrations.AlterField(
            model_name='careprovider',
            name='county',
            field=models.CharField(choices=[('CARLOW', 'Carlow'), ('CAVAN', 'Cavan'), ('CLARE', 'Clare'), ('CORK', 'Cork'), ('DONEGAL', 'Donegal'), ('DUBLIN', 'Dublin'), ('GALWAY', 'Galway'), ('KERRY', 'Kerry'), ('KILDARE', 'Kildare'), ('KILKENNY', 'Kilkenny'), ('LAOISE', 'Laois'), ('LEITRIM', 'Leitrim'), ('LIMERICK', 'Limerick'), ('LONGFORD', 'Longford'), ('LOUTH', 'Louth'), ('MAYO', 'Mayo'), ('MEATH', 'Meath'), ('MONAGHAN', 'Monaghan'), ('OFFALY', 'Offaly'), ('ROSCOMMON', 'Roscommon'), ('SLIGO', 'Sligo'), ('TIPPERARY', 'Tipperary'), ('WATERFORD', 'Waterford'), ('WESTMEATH', 'Westmeath'), ('WEXFORD', 'Wexford'), ('WICKLOW', 'Wicklow')], default='DUBLIN', max_length=9),
        ),
        migrations.AlterField(
            model_name='careprovider',
            name='type_of_care',
            field=models.CharField(choices=[('ELDERLYCARE', 'Elderly Care'), ('GP', 'General Practioner'), ('CAREWORKER', 'Care Worker'), ('HOMECARER', 'Home Carer'), ('ORTHOPEDICS', 'Orthopedics'), ('OCCUPATIONAL', 'Occupational Therapist'), ('CHIROPODISTS', 'Chiropodists'), ('PHYSIOTHERAPY', 'Physiotherapy'), ('SWIFTCARE', 'Swift Medical Care'), ('DEMENTIA', 'Dementia Support')], default='ELDERLY CARE', max_length=25),
        ),
    ]
