# Generated by Django 3.2.16 on 2023-02-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caresearch', '0008_careprovider_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careprovider',
            name='business_name',
            field=models.CharField(default='add_business_name', max_length=100),
        ),
    ]
